Add output filedir
aspida/openapi2aspida pull request #155
Opened 2021-08-31 06:12 UTC by mochi-sann

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

https://zenn.dev/seya/articles/bf52abf0b2f5a7 のように -o のプレフィクスで出力するフォルダーを変更できるようにした
例:
```
npx openapi2aspida -i=hoge/openapi.yml -o=api/hoge/fuga
```
と設定すると`api/hoge/fuga` の下にaspidaのコードが生成されるようにしました。

2022-01-11 23:51 UTC, hashue commented
@mochi-sann プルリクエストありがとうございます
こちらベースブランチを `master` から `develop`に変更をお願いします。

2022-01-12 00:02 UTC, hashue commented
> @mochi-sann プルリクエストありがとうございます こちらベースブランチを `master` から `develop`に変更をお願いします。

こちらで対応しました。

2022-01-12 00:49 UTC, hashue requested changes

2022-01-12 00:49 UTC, hashue commented on __tests__/outputFilePath.spec.ts
> +    ).toBe('apiapi/apiapi/apiapi')
「cli の -oが null」 の場合、InputFilepathが返り値になるので、toBeの値を `apiapi`に修正してください。

2022-01-12 00:49 UTC, hashue commented on src/outputFilePath.ts
> +  InputFilepath: string
InputFilepathをInputFilePathに修正してください

2022-01-12 00:56 UTC, hashue commented
@mochi-sann 
動作することは確認したので、レビューの対応をお願いします。修正され次第マージします。

2022-01-12 03:09 UTC, mochi-sann commented
@hashue  どちらとも修正しました。確認してマージお願いします。

2022-01-12 04:04 UTC, merged

2022-01-12 04:05 UTC, hashue commented
マージしました。