fix: #156
aspida/openapi2aspida pull request #170
Opened 2022-02-15 02:03 UTC by hashue

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

Issue Number: #156

2022-02-28 07:08 UTC, LumaKernel commented
please rebase or merge main

2022-02-28 07:42 UTC, hashue commented
hum… CI is still dropping…

2022-02-28 07:44 UTC, LumaKernel commented
you may see your tests failing in your local environment now. typing `: File | ReadStream` added into main after your PR opening.

2022-02-28 07:46 UTC, hashue commented
OK. I'll check it.

2022-02-28 08:24 UTC, LumaKernel requested changes
Can you add sample to show 156 is solved? I can't see whether 156 is fixed only by diff.

2022-03-01 01:21 UTC, LumaKernel approved these changes

2022-03-01 01:21 UTC, LumaKernel commented on samples/file-array/@types/index.ts
> +  files: (File | ReadStream)[]
:+1:

2022-03-01 01:27 UTC, merged